### ISSUE TITLE
Automated testing to prevent mis-styled/etc code from being merged

### ISSUE THREAD

**Issue by towerofnix** [PullJosh/sb-edit#14]
It might be worth making use of something like [Travis CI](https://travis-ci.org/) (that's what LLK uses) to automatically let it lint and test code for incoming pull requests, so that we don't accidentally merge any code which could cause those to fail. Same for scratch-js!

**Comment by PullJosh** [comment]
This is an interesting idea, not without merit.

I think my general principle with both `scratch-js` and `sb-edit` is to keep things as simple as is reasonable. At least for the time being, I suspect that adding automated testing would take more time and effort than just dealing with problems as they happen.

Until I get burned a few times by problems that would have been solved by tests, I think it's best to avoid the increased complexity.

**Comment by PullJosh** [comment]
This idea is growing on me. (I apologize for being so dismissive previously.)

This looks to be dead simple using Github Actions. The [standard Node.js template](https://github.com/actions/starter-workflows/blob/master/ci/node.js.yml) seems like it should work with zero modification. Any objections to trying this out?

**Comment by adroitwhiz** [comment]
Sounds like a good idea to me!
