### ISSUE TITLE
Do we really want to update to v1.0.0 now?

### ISSUE THREAD

**Issue by towerofnix** [PullJosh/sb-edit#18]
I noticed the repo was just updated v1.0.0, but I'm pretty sure the API isn't stable yet! If we want to follow [semantic versioning](https://semver.org/), the next version after `0.9.0` would be `0.10.0` - only moving to `1.0.0` once we've stabilized the API and are ready to treat breaking changes as major updates.

Source btw, if you're curious:

(2.) A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and MUST NOT contain leading zeroes. X is the major version, Y is the minor version, and Z is the patch version. Each element MUST increase numerically. For instance: 1.9.0 -> 1.10.0 -> 1.11.0.
(4.) Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.
(5.) Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes.

**Comment by PullJosh** [comment]
In hindsight, that probably makes sense. Although frankly I'm not too concerned. Currently there are approximately zero people using sb-edit as a dependency and one of them is me. When the API is stable we can call it v2.0.0, and in the future I'll be more careful about versioning.

(Is it even possible to roll back a version?)

**Comment by towerofnix** [comment]
As long as you've not published this to npm I think it's basically fine to rollback. If we want to stay spec-compliant (as I'd recommend), I'd consider it far more important to stay in v0.x.y before development than to not rollback one time prior to any official release.

**Comment by PullJosh** [comment]
Okay, unpublished from npm. Will need to figure out how to undo the git tag and roll back the commit, but that sounds like a problem for tomorrow. (Advise would be wonderful!)

**Comment by towerofnix** [comment]
This looks like it's worked for loads of folx for getting rid of the git tag: https://gist.github.com/mobilemind/7883996

As for rolling back the commit, there's this that would work: https://stackoverflow.com/questions/5816688/resetting-remote-to-a-certain-commit

...but you could also just revert the 1.0.0 commit (or even just manually change the version to 0.9.0 or 0.10.0) and then push that instead, which wouldn't mess with other people's local repos if they've pulled since you pushed 1.0.0 (I haven't, but it's possible some may have).

**Comment by PullJosh** [comment]
Alright, I think everything is sorted. Thanks for keeping me organized! :P
