### ISSUE TITLE
SB3 Output

### ISSUE THREAD

**Issue by towerofnix** [PullJosh/sb-edit#28]
Input an SB3, output an SB3! Here's the todo list:

- [x] Loads of research
- [x] Sprite data & costumes
- [x] Most basic blocks
- [x] Structural changes to support sb3 (IDs for sounds & costumes, minor name changes for consistency, etc)
- [x] The rest of the input types & shadow blocks
  - **Data gathering:**
  - [x] Per-block input to default value mapping, to fill in obscured shadow blocks (this isn't sb3-specific)
  - [x] Per-block input to shadow block (primitive & non-primitive) mapping
  - [x] Add remaining extension opcodes (music, etc) to known blocks & above mappings
    - AFAIK extensions always have primitive types & no fields
    - Above might be false for micro:bit grid input though? micro:bit doesn't exist in sb-edit yet anyway, but investigate how that input works to get a better understanding of extensions
  - **Logic:**
  - [x] Fill in primitive values for unobscured shadow blocks
  - [x] Fill in non-primitive values for unobscured shadow blocks
  - [x] Fill in basic default values for obscured shadow blocks
  - [x] For obscured costumes & sounds, replace default value with the corresponding first name in the sprite
  - [x] Construct broadcast ID-name mapping when broadcast inputs encountered (they're internally stored as variables now)
- [x] Custom procedures
- [x] Code finalization
  - [x] Testing lots and lots of projects
  - [x] Extend code documentation
  - [x] Add snapshot test
  - [x] Prettify code
  - [x] Make pull request

There is already a partially-complete implementation for sb3 output; it should be completed, so that projects loaded from any format can be converted into the most common output format. (As of present, our only ([mostly](https://github.com/PullJosh/scratch-js/issues/18)) complete output is scratch-js.) Implementing a working SB3 output will also let us have a basis for implementing new similar output formats, like SB2: the code structure will likely be similar, and the understanding from solving problems in SB3 will probably be useful going forward.

I've begun an SB2 output format [here](https://github.com/towerofnix/sb-edit/tree/sb2), but I ran into some peculiarities whose solutions would probably be highlighted by completing an SB3 format. SB3 is also the format which sb-edit is natively based on, with its selection of opcodes and code structure—while implementing SB3 prompts questions like "how do we handle assets?", SB2 implies those in addition to complex questions about backporting blocks, etc. It'd be better to handle one bunch of questions at a time, so: SB3 before SB2.

I'm happy to start work on this myself, since I've already worked with sb-edit a fair bit and don't have any current project in relation to it.

**Comment by PullJosh** [comment]
> I'm happy to start work on this myself, since I've already worked with sb-edit a fair bit and don't have any current project in relation to it.

That would be wonderful!

I imagine that working on a second output type will make the shortcomings of the current code base much clearer, so feel free to take some creative liberties while you work. I'm not at all opposed to ripping out and replacing some of sb-edit's ugly innards, when you feel it's appropriate.

**Comment by towerofnix** [comment]
Oh btw @PullJosh, do you mind setting the issue assignment to me? :P

**Comment by PullJosh** [comment]
> Oh btw @PullJosh, do you mind setting the issue assignment to me? :P

Alright, that's done. Do you think it would make sense to move `scratch-js` and `sb-edit` into an organization? That way you and @adroitwhiz could be members and gain some autonomy...

**Comment by towerofnix** [comment]
@PullJosh I'm in agreement there! No particular thoughts on what it should be called, though. :P

PS: I don't want to be a bother but have you seen https://github.com/PullJosh/scratch-js/issues/43#issuecomment-579064412? Not to say we're moving discussion/issue-tracking there - we aren't - but we've been hanging out and sharing progress there; you'd certainly be welcomed :P

**Comment by PullJosh** [comment]
> we've been hanging out and sharing progress there; you'd certainly be welcomed :P

That sounds fun, but I have found that when I join a Discord server (or equivalent), my productivity plummets. You all are *way too interesting*. I think for the sake of progress (on life, school, and programming), I should probably abstain. :P

**Comment by adroitwhiz** [comment]
A while ago I created a GitHub organization called [Adjacent Topics](https://github.com/adjacent-topics)--would you like to join + move this stuff there?

**Comment by towerofnix** [comment]
@PullJosh That is 100% fair and understandable! :P (@adroitwhiz :eyes: if PullJosh agrees that seems like a good place to me!)

**Comment by PullJosh** [comment]
Totally on board with moving `scratch-js`, `scratch-js-website`, and `sb-edit` to the Adjacent Topics org. Just need an invite, @adroitwhiz! ;)

**Comment by towerofnix** [comment]
FYI, this is 95% complete! PR incoming once I've tested a bunch more projects and ironed out any remaining kinks. (Also, mental fyi: the PR will be *huge*. sb3 turned out to be a *much* larger project than sb2.)
