### ISSUE TITLE
Moving to Adjacent Topics

### ISSUE THREAD

**Issue by PullJosh** [PullJosh/sb-edit#31]
This package is currently published under [my name](https://www.npmjs.com/~pulljosh) on npm. Will moving this repository to @Adjacent-Topics cause any problems?

**Comment by adroitwhiz** [comment]
Sorry I didn't see this earlier! You should be able to continue publishing this under your NPM username.

**Comment by PullJosh** [comment]
Okay! I think that's probably the best setup, too, because it doesn't make sense to publish the package as `@Adjacent-Topics/sb-edit`. (I think if you publish a package under an organization it has to include the org's name...)
