### ISSUE TITLE
What does toObject do?

### ISSUE THREAD

**Issue by adroitwhiz** [PullJosh/sb-edit#36]
A lot of `sb-edit` primitives currently have a `toObject` function, which is not documented and never called. What is this function supposed to do?

**Comment by PullJosh** [comment]
Excellent question. 😛 It converts the class instance into a plain JS object. I *thought* it was being used in the tests to create snapshots, but apparently not. Should probably be removed. (Can't forget to remove [them all](https://github.com/PullJosh/sb-edit/search?q=toObject&unscoped_q=toObject)!)

**Comment by PullJosh** [comment]
I just remembered [what toObject does](https://github.com/PullJosh/scratch-js-website/blob/master/pages/api/%5BprojectId%5D/debug.ts#L30). :P Not a concern, though. That code doesn't belong here.
