### ISSUE TITLE
Creating an Intermediate Language?

### ISSUE THREAD

**Issue by callowaysutton** [PullJosh/sb-edit#7]
Are you planning to make an intermediate language, like LLVM, or just direct translation between scratch-js, Scratch 2, and Scratch 3?

**Comment by PullJosh** [comment]
Internally, that's exactly what's going on! The [`Project`](https://github.com/PullJosh/sb-edit/blob/master/src/Project.ts) class is that intermediate format, and the stuff in [`/io`](https://github.com/PullJosh/sb-edit/tree/master/src/io) is used to convert between external formats and the intermediate scratch-js version.
